.gitignore
README.md

The files in Google Drive have been moved to my own account and links updated, so there's no more reliance on Ronan's Google Drive.

First commit of HeavenMS-2! Updated README

---

src/main/java/client/MapleFamily.java
src/main/java/client/SkillFactory.java
src/main/java/client/inventory/manipulator/MapleCashidGenerator.java
src/main/java/client/newyear/NewYearCardRecord.java
src/main/java/net/server/Server.java
src/main/java/net/server/task/CouponTask.java
src/main/java/scripting/npc/NPCConversationManager.java
src/main/java/server/CashShop.java
src/main/java/server/MapleSkillbookInformationProvider.java
src/main/java/server/life/MaplePlayerNPCFactory.java
src/main/java/server/quest/MapleQuest.java

Perform a bunch of slow tasks (such as reading from WZ files) asynchronously

Improve the startup sequence

---

.dockerignore
Dockerfile
docker-compose.yml

Mounted config files docker compose and sped up image build times

---

src/main/java/server/life/MobSkill.java
src/main/java/server/life/MobSkillFactory.java

Fixes Horntail mass seduce. Thanks xinyifly.

Fix mobskill target count

---

src/main/java/client/MapleCharacter.java
src/main/java/net/server/channel/handlers/ChangeMapHandler.java
src/main/java/net/server/channel/handlers/WhisperHandler.java
src/main/java/net/server/world/World.java
src/main/java/tools/MaplePacketCreator.java

This PR focuses on WhisperHandler.
Some of the heavenms code was re-used (anti-spam, logging), the rest was all rewritten to be more readable.
Also includes proper chase functionality, admins can use "/c name" to teleport to the player's exact location.
WHISPER packets were redone to have proper flags.

Complete rework of WhisperHandler including proper chase functionality

---

config.yaml
src/main/java/config/ServerConfig.java
src/main/java/config/YamlConfig.java
src/main/java/constants/string/CharsetConstants.java
src/main/java/net/packet/ByteBufInPacket.java
src/main/java/net/packet/ByteBufOutPacket.java
src/main/java/scripting/AbstractScriptManager.java
src/main/java/tools/HexTool.java
src/test/java/net/packet/ByteBufInPacketTest.java

Respect configured charset in config and script files.

Charset fixes

---

database/sql/1-db_database.sql
database/sql/migration/monsterbook.sql
src/main/java/client/Character.java
src/main/java/client/MonsterBook.java

Use upsert instead of delete -> insert, and use existing connection for proper rollback in case of failure.

Improve monsterbook saving

---

config.yaml
src/main/java/net/server/Server.java
src/main/java/net/server/handlers/login/ViewAllCharHandler.java
src/main/java/net/server/world/World.java
src/main/java/tools/PacketCreator.java

No longer stuck waiting for 10 seconds when there's more than one world.
Thanks to Lehava#4668 for finding the correct packet structure.

Fix 'View all characters' transition

---

scripts/npc/2091005.js
scripts/portal/dojang_up.js
src/main/java/scripting/npc/NPCScriptManager.java
src/main/java/scripting/portal/PortalScriptManager.java

Fix broken dojo scripts due to map constants

---

config.yaml
src/main/java/client/Character.java
src/main/java/client/Client.java
src/main/java/config/ServerConfig.java
src/main/java/net/server/channel/handlers/ItemMoveHandler.java
src/main/java/net/server/channel/handlers/PlayerLoggedinHandler.java
src/main/java/net/server/task/CharacterHpDecreaseTask.java
src/main/java/net/server/world/World.java
src/main/java/server/maps/MapleMap.java

Merges hpDec schedules at character into a world schedule.

Wrap around hpDec schedules

---

scripts/npc/1063017.js

Fix NPC script at end of Puppeteer's Secret Passage (910510100)

---

scripts/npc/1061012.js
scripts/npc/2013001.js
scripts/npc/2030006_old.js
scripts/npc/2094002.js
scripts/npc/2101014.js
scripts/npc/9040003.js
scripts/npc/9040006.js
scripts/npc/9040009.js
scripts/portal/EBoat1.js
scripts/portal/EBoat2.js
scripts/portal/OBoat1.js
scripts/portal/OBoat2.js
scripts/portal/davy_next1.js
scripts/portal/elevator.js
scripts/portal/kinggate2_open.js
scripts/portal/kinggate_open.js
scripts/reactor/9108000.js
scripts/reactor/9108001.js
scripts/reactor/9108002.js
scripts/reactor/9108003.js
scripts/reactor/9108004.js
scripts/reactor/9108005.js
scripts/reactor/9208000.js
scripts/reactor/9208001.js
scripts/reactor/9208002.js

Fix helios tower elevator portal script

---

scripts/npc/2090103.js
scripts/npc/2100008.js
scripts/npc/9120102.js
scripts/npc/9200100.js
scripts/npc/9200101.js
scripts/npc/9200102.js
scripts/npc/9201017.js
scripts/npc/9201062.js
scripts/npc/9270026.js

Fix one-time cosmetic lens coupon not working for female characters

---

src/main/java/client/inventory/Pet.java
src/main/java/constants/game/ExpTable.java
src/main/java/scripting/AbstractPlayerInteraction.java
src/main/java/server/quest/actions/PetSpeedAction.java
src/main/java/server/quest/requirements/MinTamenessRequirement.java
src/main/java/tools/PacketCreator.java

An official-like name and packet structure

Analyze pet packet structure correctly

---

pom.xml
src/main/java/scripting/AbstractScriptManager.java
src/test/java/scripting/ScriptEvaluationTest.java

Fix scripts containing non-ASCII characters, add tests

---

src/main/java/client/Character.java
src/main/java/client/command/commands/gm2/MobSkillCommand.java
src/main/java/client/command/commands/gm3/DebuffCommand.java
src/main/java/net/server/channel/handlers/AbstractDealDamageHandler.java
src/main/java/net/server/channel/handlers/MoveLifeHandler.java
src/main/java/net/server/channel/handlers/TakeDamageHandler.java
src/main/java/scripting/AbstractPlayerInteraction.java
src/main/java/server/StatEffect.java
src/main/java/server/life/LifeFactory.java
src/main/java/server/life/MobSkillFactory.java
src/main/java/server/life/MobSkillType.java
src/main/java/server/partyquest/CarnivalFactory.java
src/main/java/tools/mapletools/MonsterStatFetcher.java
src/test/java/server/life/MobSkillFactoryTest.java

Fix issues caused by mob skill refactor

---

src/main/java/client/Character.java

Fix dead people could be revived with a party hp potion

---

scripts/quest/4659.js
scripts/quest/8189.js

Fixes quests 4659 (Robo Upgrade!) and 8189 (Pet's Re-Evolution)
Reported in Discord by PaperMaker:
```
Completing Baby Robo upgrade quest (Robo Upgrade!) and nothing happened.
On server there was this error:
06:36:12.760 [nioEventLoopGroup-3-11] ERROR quest.QuestScriptManager - Error ending quest script: 4659
javax.script.ScriptException: org.graalvm.polyglot.PolyglotException: TypeError: invokeMember (getCloseness) on client.inventory.Pet@7d67fe09 failed due to: Unknown identifier: getCloseness
at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.toScriptException(GraalJSScriptEngine.java:503) ~[Server.jar:?]
at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.invokeFunction(GraalJSScriptEngine.java:578) ~[Server.jar:?]
at …
```

Fix reported bugs in pet quests

---

src/main/java/client/Character.java
src/main/java/server/maps/MiniGame.java

The owner of the room would get stuck if the visitor left the miniroom by closing the game

Fix MiniGame Error

---

config.yaml
src/main/java/client/Character.java
src/main/java/config/ServerConfig.java

Added a toggle to show the NX gained when looting NX coupons from monster drops.
Notes:
This is my first PR to this project as well as with Java, so please let me know if there's anything extra I need to do/commit.
Thanks!

Feature/toggle NX gain message

---

scripts/npc/9201115.js

Fix error summoning master guardians on CWKPQ last stage

---

src/main/java/net/server/channel/handlers/ChangeMapHandler.java

Fix top portal in Zenumist Society (261000010) not working for GM

---

src/main/java/net/server/channel/handlers/WeddingHandler.java

PoC for the glitch:
https://www.youtube.com/watch?v=EoVGQtMkJOA&ab_channel=ThirtyOneFifty

Fix dupe glitch with wedding

---

src/main/java/client/Character.java

Removing the level up messages as it's non GMS like and I personally found it quite outdated and a tad cringey at times.

Removed level up messages as it is non GMS like and a bit cringey

---

src/main/java/net/server/channel/handlers/MTSHandler.java
src/main/java/server/MTSItemInfo.java

Fix MTS sql syntax error and month error. Remove old API and use LocalDate

Fix MTS sql syntax error and month error

---

config.yaml
database/sql/1-db_database.sql
src/main/java/client/Character.java
src/main/java/config/ServerConfig.java
src/main/java/server/ExpLogger.java

made the loggging work with a thread on low-priority

added logs for character exp gain

---

src/main/java/server/ItemInformationProvider.java

Small change to reduce code duplication and make it easier to add hairs/faces from future versions.

use isFace and isHair in ItemInformationProvider.getStringData

---

config.yaml
src/main/java/config/ServerConfig.java
src/main/java/net/server/channel/handlers/ScrollHandler.java
src/main/java/server/ItemInformationProvider.java

Fixes #210 and removes a GM option for clean slate scrolls.
Thanks Crabo for the suggested solution.

Fix able to gain infinite slots with clean slate scroll

---

src/main/java/server/life/MobSkill.java

This was previously only used for MAGIC_IMMUNITY and WEAPON_IMMUNITY for some reason? A lot of other MobSkills also have a 'prop' node in the WZ files such as; Darkness and Seduce.

Mob Skills now have a success rate

---

src/main/java/net/server/channel/handlers/AbstractDealDamageHandler.java

Added a check for a damage hack regarding lines
I've tried it on most skills/classes (normally) without triggering it. But it might still be possible to get false positives. 
Also I'm not sure if you'd want an immediate autoban, but it seems pretty clear the player is tampering with the damage here, so I thought it's okay.

Check if the amount of damage lines doesn't exceed the max (autoban)

---

src/main/java/constants/id/ItemId.java
src/main/java/server/CashShop.java
src/test/java/constants/id/ItemIdTest.java

Remove the chance to get a cash package from Cash shop surprise. Packages aren't real items and crash the client.
Resolves #241

Fix able to get package from Cash shop surprise

---

.mvn/wrapper/maven-wrapper.properties
README.md
mvnw
mvnw.cmd

Add Maven Wrapper to simplify project setup.

Add Maven Wrapper
