P0nk/Cosmic

src/main/java/net/server/channel/handlers/PetExcludeItemsHandler.java, src/main/java/net/server/channel/handlers/SkillMacroHandler.java
These exploits cause MapleCharacter.saveToDB() to fail which result in a rollback, players will be able to dupe by dropping the items on the ground before logging off.
=> Fix 2 small packet exploits

config.yaml, src/main/java/client/MapleClient.java, src/main/java/client/command/commands/gm6/WarpWorldCommand.java, src/main/java/config/ServerConfig.java, src/main/java/net/MapleServerHandler.java, src/main/java/net/server/Server.java, src/main/java/net/server/coordinator/session/MapleSessionCoordinator.java, src/main/java/net/server/handlers/login/CharSelectedHandler.java, src/main/java/net/server/handlers/login/CharSelectedWithPicHandler.java, src/main/java/net/server/handlers/login/LoginPasswordHandler.java, src/main/java/net/server/handlers/login/RegisterPicHandler.java, src/main/java/net/server/handlers/login/ViewAllCharRegisterPicHandler.java, src/main/java/net/server/handlers/login/ViewAllCharSelectedHandler.java, src/main/java/net/server/handlers/login/ViewAllCharSelectedWithPicHandler.java
Allow clients connecting from different IP domains (local/LAN/WAN) to get past login phase and clean unnecessary local server check.
=> Allow local/LAN/WAN login-phase connections

src/main/java/net/packet/ByteBufOutPacket.java, src/test/java/net/packet/ByteBufOutPacketTest.java
Big oversight that caused broadcasted (packet sent to multiple clients)
packets to only be correct for the first receiver, for example when
3 players were in the same map.
=> Fix issue with packet bytes reuse

src/main/java/net/server/Server.java
Worlds need to be initialized before families due to an interdependency
=> Fix family loading on server startup

pom.xml, src/main/java/net/server/Server.java
2.14.1 and earlier (famously) contains a RCE exploit.
=> Bump log4j to 2.15.0

scripts/npc/rebirth.js, src/main/java/client/Character.java
Resolves #37  and also fixes a bug where if you were e.g. a maxed level 120 KoC character, you couldn't rebirth (replaced level = 200 check with level = getMaxClassLevel())
Updated NPC menu for path selection
Updated NPC text for job level check
=> Update rebirth NPC to allow path selection

src/main/java/client/inventory/Pet.java, src/main/java/net/server/channel/handlers/UseCashItemHandler.java
Resolves #103 
Adds a boolean forceEnjoy parameter to the Pet.gainClosenessFullness() method, as well as an overload to keep default functionality and prevent a breaking change.
(PS - you guys really have made PS development so easy to get going.  It's so much easier than when I tried to do this stuff 10 years ago.  Thank you for that!!)
=> Allow pet cash food to increase closeness even when pet fullness is maxed

scripts/map/onUserEnter/explorationPoint.js, src/main/java/scripting/map/MapScriptMethods.java
This was a fun one...
The explorer title quests (e.g. Beginner Explorer - Quest IDs 29005, 29006, 29007, 29008, 29009, 29010, 29011, 29014) (excludes titles that are a combination of other titles) all have an `infoex` and `infoNumber` end condition.  `infoex` stores the number of regions that need to be visited; `infoNumber` stores a pointer to a secondary, internal-only quest ID for tracking progress (I think this is usually the same as the primary quest ID).  In `canQuestByInfoProgress()`, this `infoNumber` "quest" is whose progress is checked against `infoex`.
No progress was being set for these anywhere - I added the quest update to the same handler that registers the medal maps as being visited in the first place.
Also fixes a bug where the Ludus Lake Explorer quest can't be …
=> Fix implementation of primary explorer title quests

scripts/reactor/1029000.js, src/main/java/scripting/reactor/ReactorActionManager.java
Fixes #132 
Confirmed that hitting the stones do not grant XP or drops from the Jr. Boogies.  I did add a second `killMonster()` method to allow for a reactor that kills mobs to also drop, just in case there are cases where that's useful, but it's just not used here.
I also noticed these reactors don't quite finish their animation, not sure where that issue lies - but it occurs regardless of this change.
=> Add handler for Land of Wild Boar's ritual stones

scripts/reactor/1029000.js
Per note from @tim78245 in #135 -- this updates the reactors to function the same as they did in EMS (which is presumably the same as they worked in GMS?).  Both reactors must be destroyed, and the message has been updated to match.
(Ignore the NPCs :-) Just from some other testing)
=> Update ritual stone reactor script (see PR 135 discussion)

src/main/java/constants/id/MapId.java
Fixes https://github.com/P0nk/Cosmic/issues/113
60000 references an old version of Southperry that is inaccessible normally.
2000000 points to the "real" one.
=> Fix MapId for Southperry from old inaccessible map to correct one

scripts/event/q3239.js, scripts/npc/2040003.js, scripts/portal/ludi021.js
* Fixes bug in script for NPC 2040003 (Cheng the Assistant) where dialogue was not disposed
* Adds a default portal handler for the exit portal in map 922000009 (Hidden Street: Secret Passage), which allows for compatibility with clean WZ files
* Reworks quest 3239 (The Missing Mechanical Parts) to be an instanced event.  This is how it is/was in the original MS as far as I can tell from these two YT videos: [[1]](https://www.youtube.com/watch?v=Vtb37mYbxTY&t=17s) and [[2]](https://www.youtube.com/watch?v=Vtb37mYbxTY&t=17s).  Have confirmed that the instances work appropriately (does not warp whole party, only the active user; can have two separate and unrelated instances from different characters in the same world/channel)
Re: the portal handler script - I am not sure what that portal …
=> Rework quest 3239: The Missing Mechanical Parts

.github/workflows/bump-version.yml, .github/workflows/run-build.yml, README.md
Using this action: https://github.com/marketplace/actions/github-tag-bump The idea is that the repo will be versioned in SemVer format, such as "v0.5.3". When a PR is merged, a new version will automatically be added. The new version is generated based on the latest tag, and the part that is bumped is dictated by the merge commit message, either #major, #minor (default) or #patch.
This way I (the repo owner) has control over versioning, and other contributors don't have to bother with anything.
=> Define versioning scheme

.github/workflows/bump-version.yml
The merge commit is more suitable since it provides some context and groups up all the commits.
=> Tag the merge commit instead of last commit in the PR

handbook/Cash.txt, handbook/Etc.txt, handbook/Map.txt, handbook/Setup.txt, src/main/java/client/command/commands/gm2/IdCommand.java, src/main/java/constants/game/NpcChat.java
Fixes #158 
Turns out some handbook .txt files had wrong character encoding.
=> Fix !id command not working for certain types

src/main/java/client/processor/npc/DueyProcessor.java
On behalf of Shahar#2563
"code permits to send limitless text when sending a package with quick delivery using the npc duey, even tho the sql server stores it in a string that can only contain upto 200 chars, its better to patch this"
=> Fix exploit with Duey Send Items

Dockerfile
[The OpenJDK Docker images are deprecated](https://hub.docker.com/_/openjdk) and the following error occurs when I run `docker compose up` on Windows:
```text
=> ERROR [jar 4/6] RUN mvn -f ./pom.xml clean dependency:go-offline -Dmaven.test.skip -T 1C                                    0.4s 
------
> [jar 4/6] RUN mvn -f ./pom.xml clean dependency:go-offline -Dmaven.test.skip -T 1C:
#0 0.332 Error: dl failure on line 542
#0 0.332 Error: failed /usr/java/openjdk-17/lib/server/libjvm.so, because /usr/java/openjdk-17/lib/server/libjvm.so: file too short  
------
failed to solve: executor failed running [/bin/sh -c mvn -f ./pom.xml clean dependency:go-offline -Dmaven.test.skip -T 1C]: exit code: 6
```
Switching to the Eclipse Temurin images solves this.
=> Use Eclipse Temurin images in the Dockerfile

config.yaml, src/main/java/client/inventory/manipulator/InventoryManipulator.java, src/main/java/client/processor/npc/DueyProcessor.java, src/main/java/client/processor/npc/StorageProcessor.java, src/main/java/config/ServerConfig.java, src/main/java/net/server/channel/handlers/MesoDropHandler.java, src/main/java/server/Trade.java
To prevent abuse, GMs should be permission restricted (via GM level) to trade with other non GM players, use their storage (prevent transferring to their other characters), send via Duey and to drop items. GM level is configurable.
=> GM security changes to prevent item/mesos abuse

src/main/java/client/processor/npc/DueyProcessor.java
The database code for retrieving the account and character id of the submitted recipient returns null if the character does not exist. The calling code in the `DueyProcessor `assumes that this is never null and from inspecting the conditional checks instead is expecting -1 for not found.
This patch updates the `getAccountCharacterIdFromCNAME` method to return `(-1,-1)` in the event that the character is not found.
It also has a minor refactor of the relevant conditional checks to the control statements that consume this result. It removes the nested control flow and bails out as early as possible to reduce cognitive load.
=> Delivery System - Invalid Recipient Name Patch

src/main/java/scripting/AbstractPlayerInteraction.java
Mini-dungeons are functional for solo use but when entering with a party you get the portal sound but nothing happens. Non-leaders correctly get the notification that they must be the party leader or enter solo.
Summary: `warpParty` was missing an overload that took in the destination map and portal name. There was a solo variant on `AbstractPlayerInteraction` so modeled it after that.
Explanation:
When a party leader tries to enter the portal the Graal Javascript Engine pops an exception that it cannot find warpParty on PortalPlayerInteraction. `org.graalvm.polyglot.PolyglotException: TypeError: invokeMember (warpParty) on scripting.portal.PortalPlayerInteraction failed due to: no applicable overload found `
Portals for mini-dungeons use the script system to enter dungeons. All of the …
=> Fix mini-dungeon portals for parties

database/sql/3-db_shopupdate.sql
Thorr in Mushroom Kingdom sold an untradable "Orange Potion for Beginners" instead of a "Orange Potion". This fixes that.
=> Changes an incorrect Orange Potion ID to the correct one

src/main/java/client/Client.java, src/main/java/net/netty/ServerChannelInitializer.java, src/main/java/net/server/channel/handlers/ChangeMapHandler.java, src/main/java/net/server/coordinator/session/IpAddresses.java
The server partially supports remote players connecting & local players connecting by detecting if the ip connecting is a local/lan ip. If it is, the server then properly sends the appropiate local/lan address when doing migrations.
`evaluateRemoteAddress` completely broke that by changing the ip that the server uses to detect if such connection is local/lan to being the hosts address which will be a public ip and such then not detected as a local/lan ip.
I only tested this in 1 scenario. Where I was locally connecting to a server via `127.0.0.1` but the `HOST` was my public ip. Before this fix: crash on migration to channel server, after: successfully transitioned and loaded into henesys & cashshop.
I also noticed https://github.com/P0nk/Cosmic/blob/4fb632ecdbc4c938e21723d0911b6ff6ad3fe7a …
=> Fix masking of ip address when connecting locally

src/main/java/client/inventory/manipulator/KarmaManipulator.java
setFalg() function is designed to take arguments of type short. Forcing the short type flag to be converted to the byte type causes some errors here.
For example, the equipment merge system will make the UNTRADEABLE flag become 520, combined with the Scissors of Karma 16, and finally become 536, this value is beyond the byte range, and the mandatory variable type will cause the flag error, the specific problem I encountered is that the MERGE_UNTRADEABLE flag is lost after using the Scissors of Karma.
**The way to reproduce this problem is as follows**: 
1. take a untradable equip
2. use the equipment merge system to strengthen the equip
3. use the Scissors of Karma on the equip
4. use this equip as merge material to strengthen other equip, and you will find that it succeeds.
According to …
=> fix: error flag after use karma

src/main/java/scripting/AbstractPlayerInteraction.java
I noticed the issue when I tried to give an NX item as a quest reward.
Index out of bounds issue.
After debugging I noticed CASH was not included in the invList, changing the loop from '<' to '<=' includes CASH also.
=> BugFix: can't give CASH items to player (prepareInventoryItemList)

src/main/java/scripting/quest/QuestScriptManager.java
Wasn't able to complete remote quest (only scripted ones, wz worked). because of a check.
Expanded the check to see if a quest is autocomplete. 
Might need some refactoring for readability though.
=> Bugfix: unable to complete scipted quests remotely

src/main/java/net/packet/ByteBufInPacket.java, src/main/java/net/packet/InPacket.java, src/main/java/net/server/channel/handlers/NPCMoreTalkHandler.java, src/test/java/net/packet/ByteBufInPacketTest.java
Made this change to allow more than 127 hairs/faces to be available at the stylist NPCs, but it could be useful for other custom dialogues that involve many choices. Given that `selection` can also be read from the packet as an int, I think this change makes sense.
I'm not sure when exactly the client sends a byte vs an int for `selection`, so I've only tested it for my own use case. My guess is that a negative `selection` value is never desirable, so I think this change should be pretty safe.
=> NPCMoreTalkHandler: don't underflow selection

scripts/npc/2094002.js
When a (non-leader) party member talks to NPC Guon (2094002) in Pirate PQ, they are given the choice to leave the PQ.
Expected behavior: Pressing "End Chat" or "No" should close the dialogue.
Actual behavior: Pressing "End Chat" or "No" causes the dialogue to repeat. The only ways to exit the dialogue are to press "Yes" (and leave the PQ), quit the game, or involve GM intervention.
=> Fix bug in PPQ where non-party leader can get stuck in an NPC dialogue loop

src/main/java/net/server/channel/handlers/UseCashItemHandler.java
for sealing lock
itemId == 5060001 || itemId == 5061000 || itemId == 5061001 || itemId == 5061002 || itemId == 5061003
=> fix: item lock cant extend lock time

src/main/java/net/server/channel/handlers/CashShopSurpriseHandler.java, src/main/java/server/CashShop.java
- Added showCashInventory after a successful gachapon opening in the CashShopSurpriseHandler.
- Added getItemsSize() condition to check the inventory size before proceeding with the cash shop surprise opening
I have added the following line to show the cash inventory after a successful gachapon opening in the CashShopSurpriseHandler:
> c.sendPacket(PacketCreator.showCashInventory(c));
This line is added within the condition where **cssResult** is not null, right after sending the success packet for the Surprise box open event. This ensures that the cash inventory is displayed to the user upon a successful operation.
and I have added the following condition to check the inventory size before proceeding with the cash shop surprise opening:
> if (getItemsSize() >= 100) {
>     return null;
> …
=> Surprise Box Implementation

src/main/java/scripting/npc/NPCConversationManager.java
`TypeError` occurs when calling `gainMeso()` in NPC js scripts.
When calling `gainMeso()` in NPC js scripts, the passed `number` type parameter will be converted into `Double` type in Java. The `Double` type to `int` type casting might lose precision and thus the implicit casting is discouraged.
My solution is adding a `gainMeso(Double gain)` method in the `NPCConversationManager` class and call the `intValue()` method on the `Double` value to cast the variable explicitly, so that the `TypeError` won't occur anymore.
After this patch, I think the functionality of item makers should be fixed. By the way, I only tested Vicious (Henesys) and JM from tha Streetz (Kerning City).
#224
=> NPC: Fix type casting error for `gainMeso()` method

src/main/java/net/server/channel/handlers/CashShopSurpriseHandler.java
This reverts the hacky solution made in db82cbcfae6f4eca0dc8e21b7f0de4c182b75a14
Update cash shop surprise count using the existing packet instead of a manual cash shop inventory refresh (which revealed the opened item prematurely).
=> Fix cash shop surprise count not properly updated on usage

pom.xml, src/main/java/client/Character.java, src/main/java/net/packet/ByteBufInPacket.java, src/main/java/net/packet/ByteBufOutPacket.java, src/main/java/net/server/channel/handlers/CashOperationHandler.java, src/main/java/net/server/channel/handlers/CashShopSurpriseHandler.java, src/main/java/net/server/channel/handlers/MTSHandler.java, src/main/java/server/CashShop.java, src/main/java/tools/PacketCreator.java, src/test/java/net/packet/ByteBufInPacketTest.java, src/test/java/net/packet/ByteBufOutPacketTest.java, src/test/java/net/server/channel/handlers/CashShopSurpriseHandlerTest.java, src/test/java/testutil/AnyValues.java, src/test/java/testutil/HandlerTest.java, src/test/java/testutil/Items.java, src/test/java/testutil/Packets.java
- #242 fixed Cash shop surprise count being properly updated on usage. What it didn't fix was removing the item once the last Cash shop surprise is used. This PR fixes that.
- Minor refactoring of Cash shop and the relevant handler to improve readability
- Tests for CashShopSurpriseHandler. 
- No tests for Cash shop due to it not being testable due to DB queries in its constructor. Have to revisit this once the database has been reworked.
- Use the selected Cash shop surprise instead of always the first one.
=> Fix using the last Cash shop surprise not removing the item

src/main/java/client/Character.java
Fix Energy charge crashing certain other players when attacking a mob and gaining charge.
Crabo in #bug-report (2024-06-10):
"(...) this will crash everyone in the map besides the bucc and 1 character, when a bucc (or TB) charges energy and a character with an ID that's a multiple of 102 is in the same map (and the energy reaches that number so if character ID is 204 it will reach that after 2 hits and DC the whole map besides the bucc and that char with id 204).
Thanks to others for helping me fix it. Thought I'd report it!"
=> Fix Energy charge crashing certain other players

.gitignore, scripts/npc/2101015.js, src/main/java/net/server/channel/handlers/UseCatchItemHandler.java
The score counting of Ariant Coliseum is broken. Score of a player isn't updated after catching a monster.
Ariant score should be updated whenever a player catching a monster.
Players can't exchange the "Palm Tree Beach Chair" after earning 100 points.
The order for checking conditions of Ariant point is wrong.
The correct order for checking conditions should be:
1.  Ariant points >= 100 => continue to exchange
2.  Ariant points + reward in this game >= 100 => hint that the player should convert the reward to points first
3.  Otherwise, the player doesn't have enough points to exchange the chair.
=> Ariant Coliseum: Fix score counting and trade conversation

src/main/java/net/server/channel/handlers/AbstractDealDamageHandler.java
Adjust delay of exploded mesos to align with vanilla. Effectively limits the animation to max 1 second and spread it across bunches of +0, +100, +200, +300 and +400 ms.
=> Fix staggered exploding mesos

src/main/java/client/processor/stat/AssignAPProcessor.java, src/test/java/client/processor/stat/AssignAPProcessorTest.java
Fixed issue where AP reset to reduce MP is allowed on the client, but disallowed on the server.
All minimum HP and MP checks on the server are now synced up with the same checks on the client-side (thanks teto on Discord for helping me find the relevant client code).
N/A
=> Fix minimum HP and MP checks on AP reset

src/main/java/server/life/MonsterInformationProvider.java, src/main/java/server/maps/MapleMap.java
Fix global drops concurrency issue. The same ArrayList is no longer shuffled on each killed monster. Rather, a new one is instantiated and populated with the global drops. Slightly inefficient but correctness is more important. Will likely revise in the future.
=> Fix global drops thread issue

config.yaml, src/main/java/tools/Randomizer.java, src/test/java/tools/RandomizerTest.java
The intention of the rand method (which is used to determine stat changes when using chaos scrolls) is to return a pseudorandom uniformly distributed int between lbound and ubound (both inclusive). The previous implementation did not work as intended when the lower bound was negative since java rounds up instead of down when casting a negative double to an int. As a result, +0 was twice as likely as any other result, and -lbound was only possible when nextDouble returned exactly 0. Adding the lower bound after the cast rather than before fixes this since the number being cast to an int will always be positive.
Also changed the CHSCROLL_STAT_RANGE from 6 to 5 in the config to be consistent with gms.
=> chaos scroll fix

src/main/java/server/ItemInformationProvider.java
Maker monster crystal level calculation is off by 1 because the level get -1 twice
`itemid = getCrystalForLevel(LifeFactory.getMonsterLevel(dropperid) - 1);`
```
private static int getCrystalForLevel(int level) {
int range = (level - 1) / 10;
if (range < 5) {
return ItemId.BASIC_MONSTER_CRYSTAL_1;
} else if (range > 11) {
return ItemId.ADVANCED_MONSTER_CRYSTAL_3;
} else {
return switch (range) {
case 5 -> ItemId.BASIC_MONSTER_CRYSTAL_2;
case 6 -> ItemId.BASIC_MONSTER_CRYSTAL_3;
case 7 -> ItemId.INTERMEDIATE_MONSTER_CRYSTAL_1;
case 8 -> ItemId.INTERMEDIATE_MONSTER_CRYSTAL_2;
case 9 -> ItemId.INTERMEDIATE_MONSTER_CRYSTAL_3;
case 10 -> ItemId.ADVANCED_MONSTER_CRYSTAL_1;
default -> ItemId.ADVANCED_MONSTER_CRYSTAL_2;
};
}
}
```
4260006 - Advanced Monster Crystal 1 - A Monster Crystal that was …
=> fix maker monster crystal level calculation

scripts/npc/9120003.js
Corrected the condition in NPC script 9120003.js by replacing cm.getMeso < price with cm.getMeso() < price to properly compare mesos against the price.
- [V ] I have performed a self-review of my code
- [V ] I have tested my changes
- [X ] I have added unit tests that prove my changes work
=> Fix incorrect method usage in NPC script (9120003.js)

src/main/java/client/Character.java
Server error when deleting a character
In-game error:
Server error:
The error is caused by the deleting character SQL, which has "missing" `server_queue` table.
I am not sure if this table ever exist or not so the easy fix here is to remove it from the SQL statement.
=> Fix missing table when deleting character
